export type MuscleGroup = "peito" | "costas" | "pernas" | "ombros" | "biceps" | "triceps" | "abdomen" | "cardio";

export type ExerciseDetail = {
  id: string;
  nome: string;
  grupo: MuscleGroup;
  grupoLabel: string;
  musculos: string[];
  instrucoes: string[];
  dicas: string[];
  equipamento: string;
  dificuldade: "iniciante" | "intermediário" | "avançado";
  tipo: "composto" | "isolado";
  alternativas: string[]; // ids of related exercises
};

const muscleGroupLabels: Record<MuscleGroup, string> = {
  peito: "Peito",
  costas: "Costas",
  pernas: "Pernas",
  ombros: "Ombros",
  biceps: "Bíceps",
  triceps: "Tríceps",
  abdomen: "Abdômen",
  cardio: "Cardio",
};

export const muscleGroupIcons: Record<MuscleGroup, string> = {
  peito: "💪",
  costas: "🔙",
  pernas: "🦵",
  ombros: "🏋️",
  biceps: "💪",
  triceps: "💪",
  abdomen: "🎯",
  cardio: "❤️",
};

export const allMuscleGroups: { key: MuscleGroup; label: string }[] = [
  { key: "peito", label: "Peito" },
  { key: "costas", label: "Costas" },
  { key: "pernas", label: "Pernas" },
  { key: "ombros", label: "Ombros" },
  { key: "biceps", label: "Bíceps" },
  { key: "triceps", label: "Tríceps" },
  { key: "abdomen", label: "Abdômen" },
  { key: "cardio", label: "Cardio" },
];

export const exerciseLibrary: ExerciseDetail[] = [
  // === PEITO ===
  {
    id: "supino-reto",
    nome: "Supino Reto",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Tríceps", "Deltóide Anterior"],
    instrucoes: [
      "Deite no banco com os pés firmes no chão",
      "Segure a barra na largura dos ombros ou um pouco mais",
      "Retire a barra do suporte e posicione acima do peito",
      "Desça a barra controladamente até tocar levemente o peito",
      "Empurre a barra para cima até estender os braços completamente",
    ],
    dicas: [
      "Mantenha as escápulas retraídas e deprimidas durante todo o movimento",
      "Não rebata a barra no peito",
      "Mantenha os pés firmemente plantados no chão",
    ],
    equipamento: "Barra e banco reto",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["supino-inclinado-halteres", "supino-maquina", "flexao"],
  },
  {
    id: "supino-inclinado-halteres",
    nome: "Supino Inclinado Halteres",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior (porção clavicular)", "Tríceps", "Deltóide Anterior"],
    instrucoes: [
      "Ajuste o banco a 30-45 graus de inclinação",
      "Segure um halter em cada mão na altura do peito",
      "Empurre os halteres para cima até estender os braços",
      "Desça controladamente até os cotovelos ficarem na linha do peito",
    ],
    dicas: [
      "Mantenha os cotovelos a 45° do corpo",
      "Não incline demais o banco para não sobrecarregar os ombros",
      "Controle o movimento na fase excêntrica",
    ],
    equipamento: "Halteres e banco inclinável",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["supino-reto", "crucifixo", "cross-over"],
  },
  {
    id: "supino-maquina",
    nome: "Supino Reto Máquina",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Tríceps", "Deltóide Anterior"],
    instrucoes: [
      "Ajuste o assento para que os pegadores fiquem na altura do peito",
      "Segure os pegadores com firmeza",
      "Empurre para frente até estender os braços",
      "Retorne controladamente à posição inicial",
    ],
    dicas: [
      "Ideal para iniciantes por guiar o movimento",
      "Mantenha as costas apoiadas no encosto",
      "Não trave os cotovelos completamente",
    ],
    equipamento: "Máquina de supino",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["supino-reto", "flexao"],
  },
  {
    id: "crucifixo",
    nome: "Crucifixo",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Deltóide Anterior"],
    instrucoes: [
      "Deite no banco reto segurando halteres com braços estendidos acima",
      "Com leve flexão nos cotovelos, abra os braços lateralmente",
      "Desça até sentir um bom alongamento no peitoral",
      "Junte os halteres novamente acima do peito contraindo o peitoral",
    ],
    dicas: [
      "Mantenha leve flexão nos cotovelos durante todo o movimento",
      "Foque na contração do peitoral ao juntar os braços",
      "Não use carga excessiva neste exercício de isolamento",
    ],
    equipamento: "Halteres e banco reto",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["cross-over", "crucifixo-maquina"],
  },
  {
    id: "crucifixo-maquina",
    nome: "Crucifixo Máquina",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Deltóide Anterior"],
    instrucoes: [
      "Sente-se na máquina com as costas apoiadas",
      "Segure os pegadores com os braços abertos",
      "Junte os braços na frente do peito",
      "Retorne controladamente à posição inicial",
    ],
    dicas: [
      "Ótimo exercício para sentir a contração do peitoral",
      "Ajuste o assento corretamente",
      "Foque na contração, não na carga",
    ],
    equipamento: "Máquina peck deck",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["crucifixo", "cross-over"],
  },
  {
    id: "cross-over",
    nome: "Cross Over",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Deltóide Anterior"],
    instrucoes: [
      "Posicione-se entre as polias com um pé à frente",
      "Segure os cabos com leve flexão nos cotovelos",
      "Cruze os braços na frente do corpo, abaixo do peito",
      "Retorne controladamente abrindo os braços",
    ],
    dicas: [
      "Mantenha o tronco levemente inclinado à frente",
      "Varie a posição da polia para trabalhar diferentes regiões do peitoral",
      "Controle o peso na volta",
    ],
    equipamento: "Crossover / Cabos",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["crucifixo", "crucifixo-maquina"],
  },
  {
    id: "flexao",
    nome: "Flexão de Braço",
    grupo: "peito",
    grupoLabel: "Peito",
    musculos: ["Peitoral Maior", "Tríceps", "Deltóide Anterior", "Core"],
    instrucoes: [
      "Posicione as mãos na largura dos ombros no chão",
      "Mantenha o corpo reto da cabeça aos pés",
      "Desça o peito até quase tocar o chão",
      "Empurre de volta à posição inicial",
    ],
    dicas: [
      "Mantenha o core ativado durante todo o movimento",
      "Não deixe o quadril cair ou subir demais",
      "Varie a largura das mãos para focar diferentes partes do peitoral",
    ],
    equipamento: "Peso corporal",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["supino-reto", "supino-maquina"],
  },

  // === COSTAS ===
  {
    id: "barra-fixa",
    nome: "Barra Fixa",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Bíceps", "Trapézio Inferior", "Romboides"],
    instrucoes: [
      "Segure a barra com pegada pronada na largura dos ombros ou mais",
      "Parta da posição de braços estendidos",
      "Puxe o corpo para cima até o queixo ultrapassar a barra",
      "Desça controladamente até estender os braços",
    ],
    dicas: [
      "Inicie o movimento puxando com as escápulas",
      "Evite balançar o corpo",
      "Se necessário, use elástico para assistência",
    ],
    equipamento: "Barra fixa",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["pulldown", "pulldown-fechado"],
  },
  {
    id: "pulldown",
    nome: "Pulldown",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Bíceps", "Trapézio Inferior"],
    instrucoes: [
      "Sente-se na máquina e ajuste a almofada nas coxas",
      "Segure a barra com pegada pronada aberta",
      "Puxe a barra até a parte superior do peito",
      "Retorne controladamente à posição inicial",
    ],
    dicas: [
      "Não incline o tronco demais para trás",
      "Foque em puxar com os cotovelos, não com as mãos",
      "Mantenha o peito aberto",
    ],
    equipamento: "Máquina de pulldown",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["barra-fixa", "pulldown-fechado"],
  },
  {
    id: "pulldown-fechado",
    nome: "Pulldown Pegada Fechada",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal (inferior)", "Bíceps", "Romboides"],
    instrucoes: [
      "Use o triângulo ou barra com pegada fechada",
      "Puxe em direção ao peito inferior",
      "Mantenha os cotovelos próximos ao corpo",
      "Retorne controladamente",
    ],
    dicas: [
      "Foco na porção inferior do dorsal",
      "Mantenha o tronco levemente inclinado",
      "Aperte as escápulas no final do movimento",
    ],
    equipamento: "Máquina de pulldown com triângulo",
    dificuldade: "avançado",
    tipo: "composto",
    alternativas: ["pulldown", "barra-fixa"],
  },
  {
    id: "remada-curvada",
    nome: "Remada Curvada",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Trapézio", "Romboides", "Bíceps"],
    instrucoes: [
      "Segure a barra com pegada supinada ou pronada",
      "Incline o tronco a 45° com joelhos levemente flexionados",
      "Puxe a barra em direção ao abdômen",
      "Desça controladamente até estender os braços",
    ],
    dicas: [
      "Mantenha a coluna neutra durante todo o movimento",
      "Não use impulso com o tronco",
      "Aperte as escápulas no topo do movimento",
    ],
    equipamento: "Barra",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["remada-maquina", "remada-unilateral"],
  },
  {
    id: "remada-maquina",
    nome: "Remada Máquina",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Trapézio", "Bíceps"],
    instrucoes: [
      "Ajuste o apoio de peito e o assento",
      "Segure os pegadores com firmeza",
      "Puxe em direção ao abdômen",
      "Retorne controladamente",
    ],
    dicas: [
      "Mantenha o peito apoiado no encosto",
      "Ideal para iniciantes aprender o padrão de remada",
      "Foque na contração das costas",
    ],
    equipamento: "Máquina de remada",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["remada-curvada", "remada-unilateral"],
  },
  {
    id: "remada-unilateral",
    nome: "Remada Unilateral",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Romboides", "Bíceps"],
    instrucoes: [
      "Apoie um joelho e uma mão no banco",
      "Segure o halter com a mão livre",
      "Puxe o halter em direção ao quadril",
      "Desça controladamente",
    ],
    dicas: [
      "Mantenha as costas paralelas ao chão",
      "Não rotacione o tronco",
      "Puxe com o cotovelo, não com a mão",
    ],
    equipamento: "Halter e banco",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["remada-curvada", "remada-maquina"],
  },
  {
    id: "remada-baixa",
    nome: "Remada Baixa",
    grupo: "costas",
    grupoLabel: "Costas",
    musculos: ["Grande Dorsal", "Romboides", "Trapézio", "Bíceps"],
    instrucoes: [
      "Sente-se na máquina com pés apoiados",
      "Segure o triângulo ou barra com braços estendidos",
      "Puxe em direção ao umbigo",
      "Retorne controladamente à posição inicial",
    ],
    dicas: [
      "Não balance o tronco",
      "Mantenha o peito aberto",
      "Foque na contração das escápulas",
    ],
    equipamento: "Cabo baixo",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["remada-curvada", "remada-maquina"],
  },

  // === PERNAS ===
  {
    id: "agachamento-livre",
    nome: "Agachamento Livre",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Quadríceps", "Glúteos", "Isquiotibiais", "Core"],
    instrucoes: [
      "Posicione a barra nas costas, apoiada nos trapézios",
      "Pés na largura dos ombros, pontas levemente voltadas para fora",
      "Agache quebrando primeiro no quadril, depois nos joelhos",
      "Desça até pelo menos o paralelo (coxas paralelas ao chão)",
      "Empurre o chão com os pés para subir mantendo o peito erguido",
    ],
    dicas: [
      "Mantenha a coluna neutra durante todo o movimento",
      "Joelhos devem acompanhar a direção dos pés",
      "Respire fundo antes de descer e expire ao subir",
    ],
    equipamento: "Barra e rack",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["leg-press", "agachamento-bulgaro", "agachamento-goblet"],
  },
  {
    id: "leg-press",
    nome: "Leg Press 45°",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Quadríceps", "Glúteos", "Isquiotibiais"],
    instrucoes: [
      "Sente-se na máquina com as costas bem apoiadas",
      "Posicione os pés na plataforma na largura dos ombros",
      "Destrave a plataforma e desça controladamente",
      "Empurre de volta até quase estender as pernas",
    ],
    dicas: [
      "Não trave os joelhos completamente",
      "Varie a posição dos pés para enfatizar diferentes músculos",
      "Mantenha a lombar apoiada no banco",
    ],
    equipamento: "Máquina leg press",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["agachamento-livre", "agachamento-goblet"],
  },
  {
    id: "agachamento-bulgaro",
    nome: "Agachamento Búlgaro",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Quadríceps", "Glúteos", "Isquiotibiais"],
    instrucoes: [
      "Posicione um pé em um banco atrás de você",
      "Segure halteres em cada mão",
      "Desça até o joelho traseiro quase tocar o chão",
      "Empurre com a perna da frente para subir",
    ],
    dicas: [
      "Mantenha o tronco ereto",
      "Joelho da frente não deve ultrapassar muito a ponta do pé",
      "Excelente para corrigir desequilíbrios entre as pernas",
    ],
    equipamento: "Halteres e banco",
    dificuldade: "avançado",
    tipo: "composto",
    alternativas: ["agachamento-livre", "leg-press"],
  },
  {
    id: "agachamento-goblet",
    nome: "Agachamento Goblet",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Quadríceps", "Glúteos", "Core"],
    instrucoes: [
      "Segure um halter ou kettlebell na frente do peito",
      "Pés na largura dos ombros",
      "Agache mantendo o peso próximo ao corpo",
      "Suba empurrando o chão com os pés",
    ],
    dicas: [
      "Ótimo para aprender o padrão de agachamento",
      "Mantenha os cotovelos entre os joelhos no fundo",
      "Peito erguido durante todo o movimento",
    ],
    equipamento: "Halter ou kettlebell",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["agachamento-livre", "leg-press"],
  },
  {
    id: "cadeira-extensora",
    nome: "Cadeira Extensora",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Quadríceps"],
    instrucoes: [
      "Sente-se na máquina com as costas apoiadas",
      "Posicione o rolo na frente dos tornozelos",
      "Estenda as pernas até ficarem retas",
      "Retorne controladamente à posição inicial",
    ],
    dicas: [
      "Segure a contração no topo por 1 segundo",
      "Não use impulso para levantar o peso",
      "Ajuste o encosto para que os joelhos fiquem alinhados com o eixo da máquina",
    ],
    equipamento: "Cadeira extensora",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["agachamento-livre", "leg-press"],
  },
  {
    id: "mesa-flexora",
    nome: "Mesa Flexora",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Isquiotibiais"],
    instrucoes: [
      "Deite de bruços na máquina",
      "Posicione o rolo atrás dos tornozelos",
      "Flexione os joelhos trazendo os calcanhares em direção aos glúteos",
      "Retorne controladamente",
    ],
    dicas: [
      "Mantenha o quadril no banco durante todo o movimento",
      "Controle a fase excêntrica",
      "Não hiperextenda a lombar",
    ],
    equipamento: "Mesa flexora",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["stiff"],
  },
  {
    id: "stiff",
    nome: "Stiff",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Isquiotibiais", "Glúteos", "Eretores da Coluna"],
    instrucoes: [
      "Segure a barra com pegada pronada na frente das coxas",
      "Com pernas quase estendidas, incline o tronco à frente",
      "Desça a barra deslizando pelas pernas até sentir o alongamento",
      "Retorne contraindo glúteos e isquiotibiais",
    ],
    dicas: [
      "Mantenha a barra próxima ao corpo durante todo o movimento",
      "Leve flexão nos joelhos para proteger a articulação",
      "Não arredonde a coluna",
    ],
    equipamento: "Barra",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["mesa-flexora"],
  },
  {
    id: "panturrilha-pe",
    nome: "Panturrilha em Pé",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Gastrocnêmio", "Sóleo"],
    instrucoes: [
      "Posicione-se na máquina com os ombros sob as almofadas",
      "Pés na borda da plataforma, calcanhares para fora",
      "Suba na ponta dos pés o máximo possível",
      "Desça controladamente até sentir o alongamento",
    ],
    dicas: [
      "Amplitude completa é essencial",
      "Segure a contração no topo por 2 segundos",
      "Varie a posição dos pés para trabalhar diferentes porções",
    ],
    equipamento: "Máquina de panturrilha",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["panturrilha-sentado"],
  },
  {
    id: "panturrilha-sentado",
    nome: "Panturrilha Sentado",
    grupo: "pernas",
    grupoLabel: "Pernas",
    musculos: ["Sóleo"],
    instrucoes: [
      "Sente-se na máquina com os joelhos sob a almofada",
      "Suba na ponta dos pés",
      "Desça controladamente",
    ],
    dicas: [
      "Foco no sóleo, mais profundo da panturrilha",
      "Amplitude máxima para melhores resultados",
    ],
    equipamento: "Máquina de panturrilha sentado",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["panturrilha-pe"],
  },

  // === OMBROS ===
  {
    id: "desenvolvimento-militar",
    nome: "Desenvolvimento Militar",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Anterior", "Deltóide Lateral", "Tríceps"],
    instrucoes: [
      "Segure a barra ou halteres na altura dos ombros",
      "Empurre o peso acima da cabeça até estender os braços",
      "Desça controladamente até a posição inicial",
    ],
    dicas: [
      "Mantenha o core ativado para proteger a lombar",
      "Não incline o tronco para trás",
      "Estenda completamente os braços no topo",
    ],
    equipamento: "Barra ou halteres",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["desenvolvimento-arnold", "desenvolvimento-maquina"],
  },
  {
    id: "desenvolvimento-arnold",
    nome: "Desenvolvimento Arnold",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Anterior", "Deltóide Lateral", "Deltóide Posterior"],
    instrucoes: [
      "Segure os halteres na frente do peito com palmas voltadas para você",
      "Enquanto empurra para cima, rotacione as palmas para frente",
      "Estenda completamente os braços acima da cabeça",
      "Retorne fazendo o movimento inverso",
    ],
    dicas: [
      "A rotação trabalha todas as cabeças do deltóide",
      "Movimento deve ser fluido e contínuo",
      "Use carga moderada para manter a forma",
    ],
    equipamento: "Halteres",
    dificuldade: "avançado",
    tipo: "composto",
    alternativas: ["desenvolvimento-militar", "desenvolvimento-maquina"],
  },
  {
    id: "desenvolvimento-maquina",
    nome: "Desenvolvimento Máquina",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Anterior", "Deltóide Lateral", "Tríceps"],
    instrucoes: [
      "Ajuste o assento para que os pegadores fiquem na altura dos ombros",
      "Empurre acima da cabeça até estender os braços",
      "Retorne controladamente",
    ],
    dicas: [
      "Ideal para iniciantes",
      "Mantenha as costas apoiadas",
      "Não trave os cotovelos",
    ],
    equipamento: "Máquina de desenvolvimento",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["desenvolvimento-militar", "desenvolvimento-arnold"],
  },
  {
    id: "elevacao-lateral",
    nome: "Elevação Lateral",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Lateral"],
    instrucoes: [
      "Segure um halter em cada mão ao lado do corpo",
      "Com leve flexão nos cotovelos, eleve os braços lateralmente",
      "Suba até a linha dos ombros",
      "Desça controladamente",
    ],
    dicas: [
      "Não balance o corpo para levantar o peso",
      "Mantenha leve flexão nos cotovelos",
      "Conduza o movimento com os cotovelos, não com as mãos",
    ],
    equipamento: "Halteres",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["elevacao-frontal", "face-pull"],
  },
  {
    id: "elevacao-frontal",
    nome: "Elevação Frontal",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Anterior"],
    instrucoes: [
      "Segure halteres à frente das coxas",
      "Eleve alternadamente ou simultaneamente até a linha dos ombros",
      "Desça controladamente",
    ],
    dicas: [
      "Não use impulso com o corpo",
      "Mantenha leve flexão nos cotovelos",
      "Foque na deltóide anterior",
    ],
    equipamento: "Halteres",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["elevacao-lateral"],
  },
  {
    id: "face-pull",
    nome: "Face Pull",
    grupo: "ombros",
    grupoLabel: "Ombros",
    musculos: ["Deltóide Posterior", "Trapézio", "Infraespinhal"],
    instrucoes: [
      "Ajuste o cabo na altura do rosto",
      "Segure a corda com pegada pronada",
      "Puxe em direção ao rosto separando as pontas da corda",
      "Faça rotação externa no final do movimento",
    ],
    dicas: [
      "Excelente para saúde dos ombros",
      "Foque na rotação externa",
      "Use carga leve a moderada",
    ],
    equipamento: "Cabo com corda",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["elevacao-lateral"],
  },

  // === BÍCEPS ===
  {
    id: "rosca-direta",
    nome: "Rosca Direta",
    grupo: "biceps",
    grupoLabel: "Bíceps",
    musculos: ["Bíceps Braquial", "Braquial"],
    instrucoes: [
      "Segure a barra com pegada supinada na largura dos ombros",
      "Mantenha os cotovelos fixos ao lado do corpo",
      "Flexione os cotovelos curvando a barra até os ombros",
      "Desça controladamente até estender os braços",
    ],
    dicas: [
      "Não balance o corpo para levantar a barra",
      "Cotovelos devem permanecer fixos",
      "Controle a fase excêntrica",
    ],
    equipamento: "Barra reta ou EZ",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["rosca-martelo", "rosca-scott"],
  },
  {
    id: "rosca-martelo",
    nome: "Rosca Martelo",
    grupo: "biceps",
    grupoLabel: "Bíceps",
    musculos: ["Braquial", "Braquiorradial", "Bíceps Braquial"],
    instrucoes: [
      "Segure halteres com pegada neutra (palmas voltadas uma para outra)",
      "Flexione os cotovelos levantando os halteres alternadamente",
      "Desça controladamente",
    ],
    dicas: [
      "Trabalha mais o braquial e o braquiorradial",
      "Mantém os cotovelos fixos",
      "Ótimo para desenvolver a parte externa do braço",
    ],
    equipamento: "Halteres",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["rosca-direta", "rosca-scott"],
  },
  {
    id: "rosca-scott",
    nome: "Rosca Scott",
    grupo: "biceps",
    grupoLabel: "Bíceps",
    musculos: ["Bíceps Braquial (porção curta)", "Braquial"],
    instrucoes: [
      "Apoie os braços no banco Scott",
      "Segure a barra EZ com pegada supinada",
      "Flexione os cotovelos até contrair completamente",
      "Desça controladamente sem estender completamente",
    ],
    dicas: [
      "Isola muito bem o bíceps",
      "Não estenda completamente para proteger os tendões",
      "Use carga moderada",
    ],
    equipamento: "Barra EZ e banco Scott",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["rosca-direta", "rosca-martelo"],
  },

  // === TRÍCEPS ===
  {
    id: "triceps-corda",
    nome: "Tríceps Corda",
    grupo: "triceps",
    grupoLabel: "Tríceps",
    musculos: ["Tríceps (cabeça lateral e medial)"],
    instrucoes: [
      "Segure a corda no cabo alto",
      "Mantenha cotovelos fixos ao lado do corpo",
      "Estenda os braços empurrando a corda para baixo",
      "Abra as pontas da corda no final do movimento",
    ],
    dicas: [
      "Abra a corda no final para contração máxima",
      "Cotovelos devem permanecer fixos",
      "Não use o corpo para auxiliar o movimento",
    ],
    equipamento: "Cabo com corda",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["triceps-testa", "mergulho-paralelas"],
  },
  {
    id: "triceps-testa",
    nome: "Tríceps Testa",
    grupo: "triceps",
    grupoLabel: "Tríceps",
    musculos: ["Tríceps (cabeça longa)"],
    instrucoes: [
      "Deite no banco segurando a barra EZ com braços estendidos",
      "Flexione os cotovelos descendo a barra em direção à testa",
      "Estenda os braços retornando à posição inicial",
    ],
    dicas: [
      "Mantenha os cotovelos apontando para o teto",
      "Controle a excêntrica lentamente",
      "Foco na cabeça longa do tríceps",
    ],
    equipamento: "Barra EZ e banco",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["triceps-corda", "mergulho-paralelas"],
  },
  {
    id: "mergulho-paralelas",
    nome: "Mergulho Paralelas",
    grupo: "triceps",
    grupoLabel: "Tríceps",
    musculos: ["Tríceps", "Peitoral Inferior", "Deltóide Anterior"],
    instrucoes: [
      "Segure as barras paralelas com braços estendidos",
      "Desça flexionando os cotovelos até 90°",
      "Empurre para cima até estender os braços",
    ],
    dicas: [
      "Tronco mais ereto = mais tríceps",
      "Tronco inclinado = mais peitoral",
      "Adicione peso com cinto se necessário",
    ],
    equipamento: "Barras paralelas",
    dificuldade: "avançado",
    tipo: "composto",
    alternativas: ["triceps-testa", "triceps-corda"],
  },

  // === ABDÔMEN ===
  {
    id: "prancha-frontal",
    nome: "Prancha Frontal",
    grupo: "abdomen",
    grupoLabel: "Abdômen",
    musculos: ["Reto Abdominal", "Transverso do Abdômen", "Oblíquos"],
    instrucoes: [
      "Apoie-se nos antebraços e pontas dos pés",
      "Mantenha o corpo reto da cabeça aos pés",
      "Contraia o abdômen e mantenha a posição",
    ],
    dicas: [
      "Não deixe o quadril cair ou subir",
      "Respire normalmente durante o exercício",
      "Comece com tempos mais curtos e aumente gradualmente",
    ],
    equipamento: "Peso corporal",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["abdominal-crunch", "abdominal-bicicleta"],
  },
  {
    id: "abdominal-crunch",
    nome: "Abdominal Crunch",
    grupo: "abdomen",
    grupoLabel: "Abdômen",
    musculos: ["Reto Abdominal"],
    instrucoes: [
      "Deite de costas com joelhos flexionados e pés no chão",
      "Mãos atrás da cabeça sem puxar o pescoço",
      "Suba os ombros do chão contraindo o abdômen",
      "Desça controladamente",
    ],
    dicas: [
      "Não puxe o pescoço com as mãos",
      "Foque em contrair o abdômen, não em subir alto",
      "Expire ao subir, inspire ao descer",
    ],
    equipamento: "Peso corporal",
    dificuldade: "iniciante",
    tipo: "isolado",
    alternativas: ["prancha-frontal", "abdominal-bicicleta"],
  },
  {
    id: "abdominal-bicicleta",
    nome: "Abdominal Bicicleta",
    grupo: "abdomen",
    grupoLabel: "Abdômen",
    musculos: ["Reto Abdominal", "Oblíquos"],
    instrucoes: [
      "Deite de costas com as mãos atrás da cabeça",
      "Eleve as pernas do chão",
      "Alterne levando cotovelo ao joelho oposto",
      "Mantenha o movimento fluido e controlado",
    ],
    dicas: [
      "Trabalha muito bem os oblíquos",
      "Não apresse o movimento",
      "Mantenha a lombar pressionada contra o chão",
    ],
    equipamento: "Peso corporal",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["prancha-frontal", "abdominal-crunch"],
  },
  {
    id: "elevacao-pernas",
    nome: "Elevação de Pernas",
    grupo: "abdomen",
    grupoLabel: "Abdômen",
    musculos: ["Reto Abdominal (inferior)", "Iliopsoas"],
    instrucoes: [
      "Deite de costas com as mãos ao lado do corpo",
      "Mantenha as pernas estendidas",
      "Eleve as pernas até 90° mantendo a lombar no chão",
      "Desça controladamente sem encostar os pés no chão",
    ],
    dicas: [
      "Mantenha a lombar pressionada contra o chão",
      "Se muito difícil, flexione levemente os joelhos",
      "Controle especialmente a descida",
    ],
    equipamento: "Peso corporal",
    dificuldade: "intermediário",
    tipo: "isolado",
    alternativas: ["abdominal-crunch", "prancha-frontal"],
  },

  // === CARDIO ===
  {
    id: "corrida-esteira",
    nome: "Corrida na Esteira",
    grupo: "cardio",
    grupoLabel: "Cardio",
    musculos: ["Quadríceps", "Isquiotibiais", "Panturrilha", "Core"],
    instrucoes: [
      "Ajuste a velocidade de acordo com seu nível",
      "Comece com aquecimento de 3-5 minutos em ritmo leve",
      "Aumente gradualmente a velocidade",
      "Finalize com desaquecimento de 3 minutos",
    ],
    dicas: [
      "Mantenha a postura ereta",
      "Não segure nos apoios laterais",
      "Use calçados adequados para corrida",
    ],
    equipamento: "Esteira",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["bicicleta-ergometrica", "caminhada-inclinada"],
  },
  {
    id: "bicicleta-ergometrica",
    nome: "Bicicleta Ergométrica",
    grupo: "cardio",
    grupoLabel: "Cardio",
    musculos: ["Quadríceps", "Isquiotibiais", "Panturrilha"],
    instrucoes: [
      "Ajuste a altura do banco para extensão adequada das pernas",
      "Comece com resistência leve e aqueça por 3 minutos",
      "Mantenha a cadência entre 60-90 RPM",
      "Varie a resistência conforme o treino",
    ],
    dicas: [
      "Baixo impacto nas articulações",
      "Ótimo para quem tem problemas nos joelhos",
      "Ajuste o banco corretamente para evitar dores",
    ],
    equipamento: "Bicicleta ergométrica",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["corrida-esteira", "caminhada-inclinada"],
  },
  {
    id: "caminhada-inclinada",
    nome: "Caminhada Inclinada",
    grupo: "cardio",
    grupoLabel: "Cardio",
    musculos: ["Quadríceps", "Glúteos", "Panturrilha"],
    instrucoes: [
      "Ajuste a esteira para 8-12% de inclinação",
      "Velocidade entre 5-6 km/h",
      "Mantenha o ritmo por 20-30 minutos",
    ],
    dicas: [
      "Excelente para queima de gordura sem alto impacto",
      "Não segure nas barras laterais",
      "Mantenha postura ereta",
    ],
    equipamento: "Esteira",
    dificuldade: "iniciante",
    tipo: "composto",
    alternativas: ["corrida-esteira", "bicicleta-ergometrica"],
  },
  {
    id: "burpees",
    nome: "Burpees",
    grupo: "cardio",
    grupoLabel: "Cardio",
    musculos: ["Corpo Inteiro"],
    instrucoes: [
      "Em pé, agache e coloque as mãos no chão",
      "Salte os pés para trás ficando em posição de prancha",
      "Faça uma flexão (opcional)",
      "Salte os pés de volta e salte verticalmente",
    ],
    dicas: [
      "Exercício completo de alta intensidade",
      "Comece devagar até dominar a técnica",
      "Mantenha o core ativado durante todo o movimento",
    ],
    equipamento: "Peso corporal",
    dificuldade: "intermediário",
    tipo: "composto",
    alternativas: ["corrida-esteira"],
  },
];

export function getExerciseById(id: string): ExerciseDetail | undefined {
  return exerciseLibrary.find((e) => e.id === id);
}

export function getExercisesByGroup(grupo: MuscleGroup): ExerciseDetail[] {
  return exerciseLibrary.filter((e) => e.grupo === grupo);
}

export function searchExercises(query: string): ExerciseDetail[] {
  const q = query.toLowerCase().trim();
  if (!q) return exerciseLibrary;
  return exerciseLibrary.filter(
    (e) =>
      e.nome.toLowerCase().includes(q) ||
      e.grupoLabel.toLowerCase().includes(q) ||
      e.musculos.some((m) => m.toLowerCase().includes(q))
  );
}

export function getRelatedExercises(exerciseId: string): ExerciseDetail[] {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return [];
  return exercise.alternativas
    .map((id) => getExerciseById(id))
    .filter(Boolean) as ExerciseDetail[];
}
